"use client";

import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Sparkles, Wand2, Copy, Check, Download } from "lucide-react";
import { fetchRoles } from "@/lib/api/roles";
import { generateInterviewQuestions } from "@/lib/api/jobs";
import { ErrorState } from "@/components/ui/states";

export default function InterviewQuestionsPage() {
  const rolesQuery = useQuery({ queryKey: ["roles"], queryFn: () => fetchRoles() });
  const [roleId, setRoleId] = useState("");
  const [copied, setCopied] = useState(false);

  const mutation = useMutation({
    mutationFn: () => generateInterviewQuestions({ role_id: roleId }),
  });

  const canGenerate = roleId && !mutation.isPending;
  const questions = mutation.data?.questions;

  function copyQuestions() {
    if (!questions) return;
    navigator.clipboard.writeText(questions);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadQuestions() {
    if (!questions || !mutation.data) return;
    const blob = new Blob([questions], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `interview-questions-${mutation.data.role_name.toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <p className="text-sm text-stone-600">
        Generate a structured set of interview questions for hiring managers. Questions
        are grouped by category (warm-up, experience, situational, character, motivation)
        with notes on what to listen for.
      </p>

      {/* Controls */}
      <div className="rounded-lg border border-stone-200 bg-white p-6 space-y-4">
        <div>
          <label className="mb-1 block text-xs font-medium text-stone-600">
            Role <span className="text-red-600">*</span>
          </label>
          <select
            value={roleId}
            onChange={(e) => setRoleId(e.target.value)}
            disabled={rolesQuery.isLoading}
            className={inputCls}
          >
            <option value="">
              {rolesQuery.isLoading ? "Loading…" : "Select a role"}
            </option>
            {rolesQuery.data?.map((r) => (
              <option key={r.id} value={r.id}>
                {r.name} ({r.unit})
              </option>
            ))}
          </select>
        </div>

        <div className="flex justify-end">
          <button
            onClick={() => mutation.mutate()}
            disabled={!canGenerate}
            className="inline-flex items-center gap-2 rounded-md bg-amber-700 px-5 py-2 text-sm font-medium text-white hover:bg-amber-800 disabled:opacity-50"
          >
            {mutation.isPending ? (
              <>
                <Sparkles className="h-4 w-4 animate-pulse" />
                Generating…
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4" />
                Generate questions
              </>
            )}
          </button>
        </div>
      </div>

      {mutation.isError && <ErrorState message={(mutation.error as Error).message} />}

      {/* Output */}
      {questions && (
        <div className="rounded-lg border border-stone-200 bg-white p-6">
          <div className="mb-4 flex items-center justify-between border-b border-stone-100 pb-3">
            <div>
              <h2 className="text-sm font-semibold text-stone-800">
                {mutation.data?.role_name} — Interview Questions
              </h2>
              <p className="text-xs text-stone-500">
                {mutation.data?.unit} unit · Generated by Claude
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={copyQuestions}
                className="inline-flex items-center gap-1.5 rounded-md border border-stone-300 bg-white px-3 py-1.5 text-xs font-medium text-stone-700 hover:bg-stone-50"
              >
                {copied ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-green-600" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5" />
                    Copy
                  </>
                )}
              </button>
              <button
                onClick={downloadQuestions}
                className="inline-flex items-center gap-1.5 rounded-md border border-stone-300 bg-white px-3 py-1.5 text-xs font-medium text-stone-700 hover:bg-stone-50"
              >
                <Download className="h-3.5 w-3.5" />
                Download .txt
              </button>
            </div>
          </div>
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-stone-700">
            {questions}
          </pre>
        </div>
      )}
    </div>
  );
}

const inputCls =
  "w-full rounded-md border border-stone-300 bg-white px-3 py-2 text-sm focus:border-amber-700 focus:outline-none";